POST http://localhost:8080/api/products
Content-Type: application/json

{
  "title": "Producto Nuevo",
  "description": "Descripción del producto nuevo",
  "price": 9.99,
  "thumbnail": "url_de_la_imagen",
  "code": "123456",
  "stock": 10,
  "category": "Categoria del producto"
}


